version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roamler_api
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=roamler
      - DB_USERNAME=user
      - DB_PASSWORD=password123
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db
    networks:
      - roamler_network
    ports:
      - 8000:8000

  db:
    image: mysql:8.0
    container_name: roamler_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=roamler
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - roamler_network
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  roamler_network:
    driver: bridge

volumes:
  db_data:
